In [28]:
%matplotlib inline
import numpy as np

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#import matplotlib.pyplot as plt

In [19]:
data = datasets.load_iris()
X = data.data[:,:4]            
y = data.target

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y) #разделение данных на тренир. и тест. множества

In [21]:
for i in range(1, 5):
    clf = neighbors.KNeighborsClassifier(n_neighbors=i, weights='distance')                #создадим классификатор
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)                                                      #вычислим результат классификации

In [27]:
print("KNN: ", clf)                     
print("\nAccuracy:", accuracy_score(y_test, predictions))
print("\nConfusion matrix:\n", confusion_matrix(y_test,predictions))
print("\nClassification report:\n", classification_report(y_test, predictions))

KNN:  KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='distance')

Accuracy: 0.9736842105263158

Confusion matrix:
 [[10  0  0]
 [ 0 12  1]
 [ 0  0 15]]

Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.92      0.96        13
           2       0.94      1.00      0.97        15

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.98        38
weighted avg       0.98      0.97      0.97        38

